### ISSUE TITLE
Couldn't go to custom checkout page from cart page.

### ISSUE THREAD

**Issue by bagerathan** [woocommerce/woocommerce-gateway-klarna#126] opened 2018-07-05 14:33 UTC
The issue is for non-logged in users. WC and WP are in the latest version.

When someone adds a product to the cart and try to checkout they get redirected back to the cart page itself. It was working perfectly before upgrading to latest version of the WC and WP.

The website is hosted on WP Engine.

Thanks.

**Comment by NiklasHogefjord** [comment] 2018-07-14 21:43
Hi,
This sounds lika a configuration issue and not a bug in the plugin. I'll close this ticket.

If you don't manage to solve the issue please submit a ticket to support@krokedil.se and we will try to help you.

**Closed by NiklasHogefjord** 2018-07-14 21:43 UTC
