### ISSUE TITLE
is_order_received_page() returns false when using Klarna checkout

### ISSUE THREAD

**Issue by duracelltomi** [woocommerce/woocommerce-gateway-klarna#51] opened 2016-11-05 06:54 UTC
### Expected behavior

The conditional WooCommerce tag is_order_received_page() returns true on the page that informs the visitor about a successful purchase:
https://docs.woocommerce.com/wc-apidocs/source-function-is_order_received_page.html#191-199

This tag is being used by many plugins and themes to include additional codes on this "thankyou" page.

### Actual behavior

With Klarna checkout this conditional tag returns false which prevents certain plugins and themes to do their work.

### Steps to reproduce the behavior

1. Install DuracellTomi's Google Tag Manager for WordPress
2. Activate either classic or enhanced ecommerce under the Integrations/WooCommerce tab
3. Checkout using Klarna
4. is_order_received_page() will return false after a successful payment on the thankyou page

### WordPress version

Any

### WooCommerce version

Any

### Klarna country

Any

**Comment by slobodan** [comment] 2016-11-07 07:15
@duracelltomi thank you for reporting this issue. Our approach was to just replicate the hooks from WooCommerce's thank you page in our thank you page, but I see how this can be a problem with the conditional function. Working on a fix.

**Comment by slobodan** [comment] 2017-02-20 19:37
Fixed in 2.2.3

**Comment by duracelltomi** [comment] 2017-05-02 05:26
Hi @slobodan,

It seems to me that with WooCommerce 3.0 this issue has been returned.
I've got reports from Klarna users missing order data again.

One addition that you might want to use: I was able to add a modification into the WooCommerce core that adds a WP filter to the is_order_received_page() function. You could hook in to that filter and return "true" in case the user is on your own thankyou page:

https://github.com/woocommerce/woocommerce/blob/c743cd80b7610bcbd372a89e441beec8f22dc101/includes/wc-conditional-functions.php#L198

Thanks,
Thomas

**Comment by slobodan** [comment] 2017-07-17 11:10
@duracelltomi Sorry for late reply, I missed your comment. Also, if there are any future issues, please open them in our repo instead:

https://github.com/krokedil/woocommerce-gateway-klarna

Since that's the one we use for active development. 

Working on the issue you reported now, thanks for letting me know.

**Comment by slobodan** [comment] 2017-07-17 12:19
@duracelltomi after testing this issue for a while, I wasn't able to reproduce it. 

Even without overwriting ```is_order_received_page``` function, or using the filter you introduced, ```is_order_received_page``` returns true, since both conditions are true in Klarna Checkout thank you page:

* ```is_page( wc_get_page_id( 'checkout' ) )```
* ```isset( $wp->query_vars['order-received'] )```

The second one is obvious, and the first check we handle in ```class-klarna-checkout.php``` in ```change_checkout_page_id``` method.

Could you check which one it is that fails?

**Comment by duracelltomi** [comment] 2017-07-18 14:55
Hi slobodan,

My biggest problem is that I can only test this kind of behavior on websites I do not own as I do not have direct access to your payment system. Do you have any sandbox environment where I can setup my own test account and use a test card or any test account to pay on a test site of mine?

I would love to help and test but without this, I always need to find a user who has Klarna enabled AND using WordPress AND using my plugin and this is not trivial :-)

Thomas

**Comment by slobodan** [comment] 2017-07-19 09:58
Sure thing, can you give me your email address so I can send it over?

**Comment by duracelltomi** [comment] 2017-07-19 14:25
Thanks, I've sent you an email

**Comment by slobodan** [comment] 2017-07-20 11:25
Confirmed to work as expected after tests.

**Closed by slobodan** 2017-07-20 11:25 UTC
